/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoEntryBodyRouteImport } from './routes/demo/entry-body'
import { Route as DemoEntryLengthRouteImport } from './routes/demo/entry-length'
import { Route as DemoExampleLabelRouteImport } from './routes/demo/example-label'
import { Route as DemoKitchenSinkRouteImport } from './routes/demo/kitchen-sink'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEntryBodyRoute = DemoEntryBodyRouteImport.update({
  id: '/demo/entry-body',
  path: '/demo/entry-body',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEntryLengthRoute = DemoEntryLengthRouteImport.update({
  id: '/demo/entry-length',
  path: '/demo/entry-length',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoExampleLabelRoute = DemoExampleLabelRouteImport.update({
  id: '/demo/example-label',
  path: '/demo/example-label',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKitchenSinkRoute = DemoKitchenSinkRouteImport.update({
  id: '/demo/kitchen-sink',
  path: '/demo/kitchen-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/entry-body': typeof DemoEntryBodyRoute
  '/demo/entry-length': typeof DemoEntryLengthRoute
  '/demo/example-label': typeof DemoExampleLabelRoute
  '/demo/kitchen-sink': typeof DemoKitchenSinkRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/entry-body': typeof DemoEntryBodyRoute
  '/demo/entry-length': typeof DemoEntryLengthRoute
  '/demo/example-label': typeof DemoExampleLabelRoute
  '/demo/kitchen-sink': typeof DemoKitchenSinkRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/blog': typeof BlogIndexRoute
  '/demo': typeof DemoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/playground': typeof PlaygroundRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/entry-body': typeof DemoEntryBodyRoute
  '/demo/entry-length': typeof DemoEntryLengthRoute
  '/demo/example-label': typeof DemoExampleLabelRoute
  '/demo/kitchen-sink': typeof DemoKitchenSinkRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/blog/': typeof BlogIndexRoute
  '/demo/': typeof DemoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/playground'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/demo/entry-body'
    | '/demo/entry-length'
    | '/demo/example-label'
    | '/demo/kitchen-sink'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/blog/'
    | '/demo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/playground'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/demo/entry-body'
    | '/demo/entry-length'
    | '/demo/example-label'
    | '/demo/kitchen-sink'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/blog'
    | '/demo'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/playground'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/search'
    | '/blog/$slug'
    | '/demo/entry-body'
    | '/demo/entry-length'
    | '/demo/example-label'
    | '/demo/kitchen-sink'
    | '/docs/$'
    | '/docs/{$}.md'
    | '/blog/'
    | '/demo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PlaygroundRoute: typeof PlaygroundRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoEntryBodyRoute: typeof DemoEntryBodyRoute
  DemoEntryLengthRoute: typeof DemoEntryLengthRoute
  DemoExampleLabelRoute: typeof DemoExampleLabelRoute
  DemoKitchenSinkRoute: typeof DemoKitchenSinkRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/entry-body': {
      id: '/demo/entry-body'
      path: '/demo/entry-body'
      fullPath: '/demo/entry-body'
      preLoaderRoute: typeof DemoEntryBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/entry-length': {
      id: '/demo/entry-length'
      path: '/demo/entry-length'
      fullPath: '/demo/entry-length'
      preLoaderRoute: typeof DemoEntryLengthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/example-label': {
      id: '/demo/example-label'
      path: '/demo/example-label'
      fullPath: '/demo/example-label'
      preLoaderRoute: typeof DemoExampleLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/kitchen-sink': {
      id: '/demo/kitchen-sink'
      path: '/demo/kitchen-sink'
      fullPath: '/demo/kitchen-sink'
      preLoaderRoute: typeof DemoKitchenSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PlaygroundRoute: PlaygroundRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoEntryBodyRoute: DemoEntryBodyRoute,
  DemoEntryLengthRoute: DemoEntryLengthRoute,
  DemoExampleLabelRoute: DemoExampleLabelRoute,
  DemoKitchenSinkRoute: DemoKitchenSinkRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  BlogIndexRoute: BlogIndexRoute,
  DemoIndexRoute: DemoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
